FROM python:3.14-alpine

COPY * /opt/

RUN pip install -r /opt/requirements.txt

USER 1000

WORKDIR /opt

ENV DB_PATH=/data/db.sqlite

ENTRYPOINT ["gunicorn", "app:app", "--bind=[::]:8000", "--no-control-socket"]
